spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test02?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.pojo

